Docs improvements
spiral/roadrunner-docs pull request #138
Opened 2023-04-28 15:29 UTC by butschster

2023-05-02 11:06 UTC, butschster commented on docs/en/customization/build.md
> +To facilitate this process, we have developed the **Velox** tool, which enables developers to build a RoadRunner server
Simplify

2023-05-02 15:09 UTC, rustatian commented on docs/en/plugins/grpc.md
> +1. **Proto-plugin `protoc-gen-php-grpc`:** This is a plugin for the protoc compiler that generates PHP code from a gRPC
```suggestion
1. **protoc-plugin `protoc-gen-php-grpc`:** This is a plugin for the protoc compiler that generates PHP code from a gRPC
```

2023-05-02 15:09 UTC, rustatian commented on docs/en/plugins/grpc.md
> +2. **The server:** This is a server that starts PHP workers and listens for incoming gRPC requests. It receives requests
```suggestion
2. **gRPC server:** This is a server that starts PHP workers and listens for incoming gRPC requests. It receives requests
```

2023-05-02 15:09 UTC, rustatian commented on docs/en/plugins/grpc.md
> +# Plugins — gRPC
We might also mention (if you think it worth mentioning in this section) that all of our proto-API can be found here: https://buf.build/roadrunner-server/api

2023-05-02 15:09 UTC, rustatian commented on docs/en/plugins/grpc.md
> +### Minimal dependencies:
I guess we can delete this section, I created it for the custom plugins, but it's not needed anymore.

2023-05-03 07:13 UTC, rustatian commented on docs/en/customization/build.md
> +authenticate with access tokens.
The developer needs GitHub token in any case (to download all plugins). Anonymous access have a limit of the 60 req per hour IIRC.

2023-05-03 07:13 UTC, rustatian commented on docs/en/customization/build.md
> +We created a tool called **Velox** that lets developers build a RoadRunner server binary. They do this by using a
They? I guess it's better to use: `Velox uses a configuration file that contains the list of plugins that are available in GitHub or GitLab repositories`

2023-05-03 07:13 UTC, rustatian commented on docs/en/customization/build.md
> +You can simplify the build process by using the Docker image. It builds the application server and starts it
It builds?
Velox builds the RoadRunner...
Velox doesn't start the RoadRunner after build, just puts it to the output folder specified by the user.

2023-05-03 07:13 UTC, rustatian commented on docs/en/customization/build.md
> +RUN vx build -c plugins.toml -o /usr/bin/
velox.toml file exists in the repository, this link refers to it: https://github.com/roadrunner-server/velox/blob/master/velox_rr_v2023.toml
(I guess it's better to use `velox_rr_v2023` in this context)

2023-05-03 07:13 UTC, rustatian commented on docs/en/php/developer.md
> +> When using the `pool.debug` option in RoadRunner, it is important to note that the `pool.num_workers` section will not
I guess we might note here, that all pool section would work differently. All options will be ignored (supervisor, max_jobs, etc)

2023-05-03 07:13 UTC, rustatian commented on docs/en/plugins/tcp.md
>  ## Principle of work
All the rest is good, thanks 👍🏻

2023-05-03 07:55 UTC, rustatian commented on docs/en/plugins/server.md
> +`jobs`, `centrifuge`, and `grpc`. The worker pools inherit all of RoadRunner's features, such as supervising, state
+ temporal

2023-05-03 07:55 UTC, rustatian commented on docs/en/plugins/server.md
> +The `on_init` section is used for application initialization or warming up before starting workers. It allows you to set
You may also note, that:
1. User may run anything with this `on_init` command. Not only roadrunner php worker (like service).
2. If the command fails, RR will log that and continue execution. So, `on_init` fail (non 0 exit code) will not interrupt the execution.

2023-05-03 07:55 UTC, rustatian commented on docs/en/plugins/server.md
> +The `user` and `group` options allow you to set the user and group that will start and own the worker process. An empty
We should also mention, that to use this functionalily, RR should be started from the root. All temporary files (http for example) would be created with the provided user/group. Root needed only to have the ability to fork process under the different user.

2023-05-03 07:55 UTC, rustatian commented on docs/en/plugins/server.md
> +using a relay. The relay can be `pipes`, `TCP`, or a `socket`. The PHP client simplifies this process by providing a
Might also mention, that `pipes` is the fastest communication transport and used by default.

2023-05-04 20:15 UTC, rustatian commented on docs/en/customization/middleware.md
> +`HTTP` and `gRPC` plugins. Moving highly loaded parts of an application, such as authentication, to middleware written
`gRPC` not middleware, but interceptors (client side). And also you might mention `temporal` here (also called interceptors).

2023-05-08 19:13 UTC, rustatian requested changes

2023-05-08 19:13 UTC, rustatian commented on docs/en/app-server/cli.md
> +rr version local (build time: development, go1.18.3), OS: linux, arch: amd64
`rr version 2023.1.2 (build time: 2023-05-04T13:19:13+0000, go1.20.4), OS: linux, arch: amd64`

2023-05-08 19:13 UTC, rustatian commented on docs/en/app-server/cli.md
> +- `-d` - starts a Golang pprof server in debug mode. This allows you to analyze the performance of your application and
Not in the `debug` mode. Just `starts a Golang profiling server`. You might also put this link as further reading: https://pkg.go.dev/net/http/pprof

2023-05-08 19:13 UTC, rustatian commented on docs/en/app-server/cli.md
> +- `-o` - allows you to override configuration keys with your values. For example, -o=http.address=:8080 will override
`-o=http.addres=8080`, without `:`.

2023-05-08 19:13 UTC, rustatian commented on docs/en/app-server/cli.md
> +- If you want to stop RoadRunner manually, you can hit `ctrl+c` for a graceful stop or hit `ctrl+c` one more time to
You may also mention that the graceful period after the first `SIGINT/TERM` or `C-c` is 30 seconds by default and might be configured here: https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L2115

2023-05-08 19:13 UTC, rustatian commented on docs/en/app-server/cli.md
> +./rr stop
It should be noted that this is only true if RR is started with `-p` option `rr server -p ..` and .pid-file exists.

2023-05-08 19:13 UTC, rustatian commented on docs/en/app-server/cli.md
>  To show the rr version, use `-v` or `--version`:
Duplicate, mentioned at the beginning of the chapter.

2023-05-08 19:13 UTC, rustatian commented on docs/en/app-server/production.md
> +  number heuristically.
... based on the available memory on the server.

2023-05-08 19:13 UTC, rustatian commented on docs/en/app-server/systemd.md
> +such as `rr.service`. This file should be placed in the `.config/systemd/user/` directory. To enable the service, you
`This file should be placed...` -> `Usually, such user unit files are located...`
This is because the `systemd` unit files don't have to be in the user's home directory. They might be here, but in most production cases they would be in `/etc/systemd`. So I would not use the word `should` in this context.

2023-05-08 19:13 UTC, rustatian commented on docs/en/customization/build.md
> +RUN vx build -c plugins.toml -o /usr/bin/
```suggestion
RUN vx build -c velox_rr_2023.toml -o /usr/bin/
```

2023-05-08 19:13 UTC, rustatian commented on docs/en/customization/embedding.md
> +stock roadrunner binary.
`roadrunner` -> `RoadRunner`. Could you please also check with `grep` or search-and-replace in your IDE the RoadRunner naming to use one name everywhere: `RoadRunner`.

2023-05-08 19:13 UTC, rustatian commented on docs/en/intro/contributing.md
> +our [Discord channel](https://discord.gg/TFeEmCs) for support from the RoadRunner maintainers and community members.
`https://discord.gg/TFeEmCs` -> `https://discord.gg/spiralphp` new link

2023-05-08 19:13 UTC, rustatian commented on docs/en/intro/features.md
> +- A Fully customizable http(s)/2 server
```suggestion
- A fully customizable http(s)/2 server
```

2023-05-08 19:13 UTC, rustatian commented on docs/en/intro/features.md
> +- Compatible with both Windows and WSL2, with support for Unix sockets (`AF_UNIX`) on Windows 10.
```suggestion
- Compatible with both Windows and WSL2, with support for Unix sockets (`AF_UNIX`) on Windows 10/11.
```

2023-05-08 19:13 UTC, rustatian commented on docs/en/kv/memcached.md
> +      addr: [ "localhost:11211", "localhost:11222" ]
```suggestion
      addr: [ "127.0.0.1:11211", "127.0.0.1:11222" ]
```

2023-05-08 19:13 UTC, rustatian commented on docs/en/lab/logger.md
> +in a friendly format. JSON encoding, on the other hand, returns messages as a JSON string without formatting. JSON
You might also mention here, that this is JSON Structured logging

2023-05-08 19:13 UTC, rustatian commented on docs/en/lab/logger.md
> +It allows configuring custom line endings for the logger. By default, the plugin uses `\n` as the line ending.
Need to mention, that `\n` is forced default. So, if you specify nothing and expecting to skip `\n`, RR will still use `\n`.

2023-05-08 19:13 UTC, rustatian commented on docs/en/lab/otel.md
> +RoadRunner offers otel (OpenTelemetry) plugin, which provides a unified standard for tracing, logging, and metrics
```suggestion
RoadRunner offers OTEL (OpenTelemetry) plugin, which provides a unified standard for tracing, logging, and metrics
```

2023-05-08 19:13 UTC, rustatian commented on docs/en/lab/otel.md
> +| **endpoint**        | a string that specifies the consumer's endpoint. The default value is `localhost:4318`.
```suggestion
| **endpoint**        | a string that specifies the consumer's endpoint. The default value is `127.0.0.1:4318`.                                                                                                                                                         |
```

2023-05-08 19:13 UTC, rustatian commented on docs/en/php/rpc.md
> +Goridge is a high-performance PHP-to-Golang library developed specifically for communication between PHP
```suggestion
Goridge is a high-performance PHP-to-Golang/Golang-to-PHP library developed specifically for communication between PHP
```

2023-05-11 13:11 UTC, merged